# This is a config for E2B sandbox template.
# You can use 'template_id' (armihoe0e2yeloofznmb) or 'template_name (vercel-demo) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='vercel-demo')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'vercel-demo' })

memory_mb = 4_096
cpu_count = 4
start_cmd = "/home/user/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vercel-demo"
template_id = "armihoe0e2yeloofznmb"
